package view;

import java.awt.Event;
import java.awt.HeadlessException;
import view.customized.ButtonTabComponent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import service.Nos;
import service.ParseHtml;
import service.Pilha;
import service.Render;
import service.navegadorService;
import view.customized.Aba;
import view.customized.AbaAnonima;

/**
 * Interface anônima do navegador.
 *
 * @author Estêvão Anderle, Lenon de Paula
 */
public class interfaceAnonima extends javax.swing.JFrame {

    navegadorService nav = new navegadorService();
    ConfigRede rede = new ConfigRede();
    Pilha pilha = new Pilha();
    Render rend = new Render();
    ParseHtml p = new ParseHtml();

    /**
     * Creates new form interfaceGrafica
     */
    public interfaceAnonima() {
        initComponents();
        if (pilha.pilhaEsquerda.empty()) {
            jBVoltar.setEnabled(false);
        }
        if (pilha.pilhaDireita.empty()) {
            jBAvancar.setEnabled(false);
        }
        //Isso faz com que ele sempre inicie centralizado
        this.setLocationRelativeTo(null);
    }

    public interfaceAnonima(String url) throws HeadlessException {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu = new javax.swing.JPopupMenu();
        jMIConfigRede = new javax.swing.JMenuItem();
        jPAcoes = new javax.swing.JPanel();
        jBUser = new javax.swing.JButton();
        jBMenu = new javax.swing.JButton();
        jBNovaAba = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTPAbas = new javax.swing.JTabbedPane();
        jPAba1 = new javax.swing.JPanel();
        jPNavegacao = new javax.swing.JPanel();
        jBVoltar = new javax.swing.JButton();
        jBAvancar = new javax.swing.JButton();
        jPUrl = new javax.swing.JPanel();
        jTFUrl = new javax.swing.JTextField();
        jBBuscarUrl = new javax.swing.JButton();
        jSPPagina = new javax.swing.JScrollPane();
        pagina = new javax.swing.JEditorPane();

        jMIConfigRede.setText("Configurar rede...");
        jMIConfigRede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConfigRedeActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMIConfigRede);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Navegador");

        jPAcoes.setBackground(new java.awt.Color(153, 153, 153));
        jPAcoes.setPreferredSize(new java.awt.Dimension(82, 78));

        jBUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/user.png"))); // NOI18N
        jBUser.setToolTipText("Logar no navegador");
        jBUser.setEnabled(false);

        jBMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/menu.png"))); // NOI18N
        jBMenu.setToolTipText("Abrir menu");
        jBMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMenuActionPerformed(evt);
            }
        });

        jBNovaAba.setText("+");
        jBNovaAba.setToolTipText("Adicionar nova aba");
        jBNovaAba.setPreferredSize(new java.awt.Dimension(43, 23));
        jBNovaAba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovaAbaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/anonimo.png"))); // NOI18N
        jLabel1.setText("Navegando em modo anônimo");

        javax.swing.GroupLayout jPAcoesLayout = new javax.swing.GroupLayout(jPAcoes);
        jPAcoes.setLayout(jPAcoesLayout);
        jPAcoesLayout.setHorizontalGroup(
            jPAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                .addComponent(jBNovaAba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPAcoesLayout.setVerticalGroup(
            jPAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAcoesLayout.createSequentialGroup()
                .addGroup(jPAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
            .addComponent(jBNovaAba, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTPAbas.setToolTipText("");
        jTPAbas.setPreferredSize(new java.awt.Dimension(23, 100));
        jTPAbas.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jTPAbasComponentRemoved(evt);
            }
        });

        jPNavegacao.setPreferredSize(new java.awt.Dimension(626, 55));

        jBVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/voltar.png"))); // NOI18N
        jBVoltar.setToolTipText("Voltar uma página");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jBAvancar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/avancar.png"))); // NOI18N
        jBAvancar.setToolTipText("Avançar uma página");
        jBAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAvancarActionPerformed(evt);
            }
        });

        jPUrl.setBackground(new java.awt.Color(255, 255, 255));

        jTFUrl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFUrlKeyPressed(evt);
            }
        });

        jBBuscarUrl.setBackground(new java.awt.Color(255, 255, 255));
        jBBuscarUrl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/busca_url.png"))); // NOI18N
        jBBuscarUrl.setToolTipText("Ir para endereço digitado");
        jBBuscarUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarUrlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPUrlLayout = new javax.swing.GroupLayout(jPUrl);
        jPUrl.setLayout(jPUrlLayout);
        jPUrlLayout.setHorizontalGroup(
            jPUrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPUrlLayout.createSequentialGroup()
                .addComponent(jTFUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jBBuscarUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPUrlLayout.setVerticalGroup(
            jPUrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPUrlLayout.createSequentialGroup()
                .addGroup(jPUrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBBuscarUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFUrl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPNavegacaoLayout = new javax.swing.GroupLayout(jPNavegacao);
        jPNavegacao.setLayout(jPNavegacaoLayout);
        jPNavegacaoLayout.setHorizontalGroup(
            jPNavegacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNavegacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPUrl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPNavegacaoLayout.setVerticalGroup(
            jPNavegacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNavegacaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPNavegacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jSPPagina.setPreferredSize(new java.awt.Dimension(593, 22));

        pagina.setEditable(false);
        pagina.setContentType(""); // NOI18N
        pagina.setToolTipText("");
        pagina.setPreferredSize(new java.awt.Dimension(593, 20));
        jSPPagina.setViewportView(pagina);

        javax.swing.GroupLayout jPAba1Layout = new javax.swing.GroupLayout(jPAba1);
        jPAba1.setLayout(jPAba1Layout);
        jPAba1Layout.setHorizontalGroup(
            jPAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPNavegacao, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
            .addGroup(jPAba1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSPPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPAba1Layout.setVerticalGroup(
            jPAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAba1Layout.createSequentialGroup()
                .addComponent(jPNavegacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSPPagina, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTPAbas.addTab("Nova Aba", jPAba1);
        int i = jTPAbas.getSelectedIndex();
        jTPAbas.setTabComponentAt(i, new ButtonTabComponent(jTPAbas));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTPAbas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTPAbas, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void verificarRequest(String address, File file) throws Exception {
        ArrayList<String> imagens = new ArrayList<String>();
        String urlAcesso = jTFUrl.getText();
        String texto = null;
        String titulo = null;
        String problema = null;
        try {
            problema = nav.urlRequest(address, file);
            if (!problema.equalsIgnoreCase(null)) {
                JOptionPane.showMessageDialog(null, problema);
                new Exception(problema);
                return;
            }
        } catch (Exception ex) {
        }
        texto = nav.urlDown(urlAcesso, file);
        titulo = p.extrairTitulo(texto);
        int aba = jTPAbas.getSelectedIndex();
        jTPAbas.setTitleAt(aba, titulo);
        imagens = p.linkImage(texto, urlAcesso);
        Nos arvore = p.parseArvore(texto, null);
        rend.render(arvore, pagina, jTFUrl);
        rend.renderTela(pagina, imagens);
    }
    private void jBBuscarUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarUrlActionPerformed
        try {
            File file = new File("page.html");
            verificarRequest(jTFUrl.getText(), file);

            if (!pilha.pilhaEsquerda.empty()) {
                jBVoltar.setEnabled(true);
            } else {
                jBVoltar.setEnabled(false);
            }
            pilha.pilhaEsquerda.push(jTFUrl.getText());
            if (evt.getSource().equals(jBBuscarUrl)) {
                pilha.limparPilhaDireita();
                jBAvancar.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jBBuscarUrlActionPerformed

    private void jTPAbasComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTPAbasComponentRemoved
        if (jTPAbas.getTabCount() <= 0) {
            System.exit(0);
        }
        if (!jBNovaAba.isEnabled()) {
            jBNovaAba.setEnabled(true);
        } else {
            jBNovaAba.setEnabled(false);
        }
    }//GEN-LAST:event_jTPAbasComponentRemoved

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        String ultimaUrl = pilha.pilhaEsquerda.empty() ? "" : pilha.voltar();
        jTFUrl.setText(ultimaUrl);
        jBBuscarUrlActionPerformed(evt);
        if (pilha.pilhaEsquerda.empty()) {
            jBVoltar.setEnabled(false);
        }
        jBAvancar.setEnabled(true);
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jBAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAvancarActionPerformed
        String proximaUrl = pilha.pilhaDireita.empty() ? "" : pilha.avancar();
        jTFUrl.setText(proximaUrl);
        jBBuscarUrlActionPerformed(evt);
        if (pilha.pilhaDireita.empty()) {
            jBAvancar.setEnabled(false);
        }
        if (pilha.pilhaEsquerda.empty()) {
            jBVoltar.setEnabled(false);
        }
    }//GEN-LAST:event_jBAvancarActionPerformed

    private void jMIConfigRedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConfigRedeActionPerformed
        rede.setVisible(true);
    }//GEN-LAST:event_jMIConfigRedeActionPerformed

    private void jTFUrlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFUrlKeyPressed
        if (evt.getKeyCode() == Event.ENTER) {
            try {
                File file = new File("page.html");
                verificarRequest(jTFUrl.getText(), file);

                if (!pilha.pilhaEsquerda.empty()) {
                    jBVoltar.setEnabled(true);
                } else {
                    jBVoltar.setEnabled(false);
                }
                pilha.pilhaEsquerda.push(jTFUrl.getText());
                if (evt.getSource().equals(jBBuscarUrl)) {
                    pilha.limparPilhaDireita();
                    jBAvancar.setEnabled(false);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jTFUrlKeyPressed

    private void jBNovaAbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovaAbaActionPerformed
        int numero = jTPAbas.getTabCount();
        if (this.getExtendedState() == 0) {
            AbaAnonima panel = new AbaAnonima();

            if (numero <= 8) {
                String titulo = "Aba " + numero;

                jTPAbas.addTab(titulo, panel);
                jTPAbas.setSelectedComponent(panel);
                int i = jTPAbas.getSelectedIndex();
                jTPAbas.setTabComponentAt(i, new ButtonTabComponent(jTPAbas));
            } else {
                int resposta = JOptionPane.showConfirmDialog(null, "Para adicionar mais abas, "
                        + "é necessário maximizar seu navegador. Deseja fazer "
                        + "isso agora?", "Deseja adicionar mais abas?", JOptionPane.YES_NO_OPTION);
                if (resposta == JOptionPane.YES_OPTION) {
                    this.setExtendedState(MAXIMIZED_BOTH);
                }
            }
        } else {
            Aba panel = new Aba();

            if (numero <= 18) {

                String titulo = "Aba " + numero;

                jTPAbas.addTab(titulo, panel);
                jTPAbas.setSelectedComponent(panel);
                int i = jTPAbas.getSelectedIndex();
                jTPAbas.setTabComponentAt(i, new ButtonTabComponent(jTPAbas));
            } else {
                JOptionPane.showMessageDialog(null, "Você alcançou o número máximo de abas");
                jBNovaAba.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jBNovaAbaActionPerformed

    private void jBMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMenuActionPerformed
        jPopupMenu.show(jBMenu, WIDTH - 105, jBMenu.getY() + 35);
    }//GEN-LAST:event_jBMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaceAnonima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaceAnonima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaceAnonima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaceAnonima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaceAnonima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAvancar;
    protected javax.swing.JButton jBBuscarUrl;
    private javax.swing.JButton jBMenu;
    private javax.swing.JButton jBNovaAba;
    private javax.swing.JButton jBUser;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMIConfigRede;
    private javax.swing.JPanel jPAba1;
    private javax.swing.JPanel jPAcoes;
    private javax.swing.JPanel jPNavegacao;
    public javax.swing.JPanel jPUrl;
    private javax.swing.JPopupMenu jPopupMenu;
    private javax.swing.JScrollPane jSPPagina;
    public javax.swing.JTextField jTFUrl;
    private javax.swing.JTabbedPane jTPAbas;
    public javax.swing.JEditorPane pagina;
    // End of variables declaration//GEN-END:variables


    /*  Alguns sites que renderizam rápido
                http://po.ta.to/
                http://www.ismycomputeron.com/
                http://www.pudim.com.br/
     */
}
