package view;

import java.awt.AWTException;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.bean.Historico;
import model.dao.historicoDAO;

/**
 * Classe que exibe e trata os históricos.
 *
 * @author Estêvão Anderle, Lenon de Paula
 */
public class MenuHistorico extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMenuHistorico
     */
    public MenuHistorico() {
        initComponents();
        //Isso faz com que ele sempre inicie centralizado
        this.setLocationRelativeTo(null);
        DefaultTableModel dtmHistorico = (DefaultTableModel) jTHistorico.getModel();
        getAllHistorico();
    }

    /**
     * Busca todos os históricos e exibe na tabela.
     */
    public void getAllHistorico() {
        DefaultTableModel dtmHistorico = (DefaultTableModel) jTHistorico.getModel();
        dtmHistorico.setNumRows(0);
        historicoDAO hDAO = new historicoDAO();

        for (Historico h : hDAO.getAll()) {
            dtmHistorico.addRow(new Object[]{
                h.getData_acesso(),
                h.getPagina(),
                h.getUrl()
            });

        }
    }

    /**
     * Busca todos os históricos, filtrando por nome.
     *
     * @param pagina nome do histórico pesquisado
     */
    public void getAllHistoricoUrl(String pagina) {
        DefaultTableModel dtmHistorico = (DefaultTableModel) jTHistorico.getModel();
        dtmHistorico.setNumRows(0);
        historicoDAO hDAO = new historicoDAO();

        for (Historico h : hDAO.getForUrl(pagina)) {
            dtmHistorico.addRow(new Object[]{
                h.getData_acesso(),
                h.getPagina(),
                h.getUrl()
            });
        }
    }

    /**
     * Busca todos os históricos, filtrando por data.
     *
     * @param data do histórico pesquisado
     */
    public void getAllHistoricoData(String data) {
        DefaultTableModel dtmHistorico = (DefaultTableModel) jTHistorico.getModel();
        dtmHistorico.setNumRows(0);
        historicoDAO hDAO = new historicoDAO();

        for (Historico h : hDAO.getForDate(data)) {
            dtmHistorico.addRow(new Object[]{
                h.getData_acesso(),
                h.getPagina(),
                h.getUrl()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCBFiltro = new javax.swing.JComboBox<>();
        jTFPesquisarHistorico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTHistorico = new javax.swing.JTable();
        jBCancelar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Histórico");
        setResizable(false);

        jCBFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Página:", "Acessado em:" }));
        jCBFiltro.setToolTipText("Filtrar por:");

        jTFPesquisarHistorico.setForeground(new java.awt.Color(153, 153, 153));
        jTFPesquisarHistorico.setText("Pesquisar no histórico");
        jTFPesquisarHistorico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFPesquisarHistoricoFocusGained(evt);
            }
        });

        jTHistorico.setAutoCreateRowSorter(true);
        jTHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Acessado em:", "Página:", "Endereço:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTHistorico.setRowSelectionAllowed(false);
        jTHistorico.getTableHeader().setReorderingAllowed(false);
        jTHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTHistoricoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTHistorico);

        jBCancelar.setText("Fechar");
        jBCancelar.setToolTipText("Fechar histórico");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCBFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFPesquisarHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBBuscar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFPesquisarHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFPesquisarHistoricoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFPesquisarHistoricoFocusGained
        if (jTFPesquisarHistorico.getText().equals("Pesquisar no histórico")) {
            jTFPesquisarHistorico.setText("");
            jTFPesquisarHistorico.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTFPesquisarHistoricoFocusGained

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        //Ao clicar no botão, ele dispara esse evento e fecha a janela.
        dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        if (String.valueOf(jCBFiltro.getSelectedItem()).equals("Página:")) {
            getAllHistoricoUrl(jTFPesquisarHistorico.getText());
        } else {
            getAllHistoricoData(jTFPesquisarHistorico.getText());
        }

    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jTHistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTHistoricoMouseClicked
        if (evt.getClickCount() == 2) {
            String url = (String) jTHistorico.getValueAt(jTHistorico.getSelectedRow(), 2);
            interfaceGrafica.adicionaUrlExterna(url);
            dispose();
        }
    }//GEN-LAST:event_jTHistoricoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuHistorico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JComboBox<String> jCBFiltro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFPesquisarHistorico;
    private javax.swing.JTable jTHistorico;
    // End of variables declaration//GEN-END:variables
}
